姓名:Android CI

在……之上:
推:
分支机构:[ "稳定" ]
pull_request:
分支机构:[ "稳定" ]

工作:
建立:

run-on:ubuntu-最新

步骤:
-uses:操作/签出@v3
-姓名:设置JDK11
uses:操作/设置-java@v3
和……一起:
java版:'11'
分布:'temurin'
缓存:Gradle

-姓名:授予gradlew的执行权限
跑:chmod+x gradlew
-姓名:使用渐变生成
跑:./gradlew构建
